import { StyleSheet, Dimensions, Platform } from "react-native";
import { Fonts } from "@/assets";
import { COLORS, SF, SH, SW, ShadowStyles } from "@/theme";
import { verticalScale, moderateScale, scale } from "react-native-size-matters";
import { RotateInDownLeft } from "react-native-reanimated";
const windowWidth = Dimensions.get("window").width;

export const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: COLORS.white,
    paddingHorizontal: SW(20),
    paddingVertical: SW(10),
  },
  headingBoldText: {
    color: COLORS.darkGrey2,
    fontFamily: Fonts.SemiBold,
    fontSize: SF(12),
  },

  titleStyle: {
    textAlign: "left",
    fontSize: SF(18),
    fontFamily: Fonts.SemiBold,
    color: COLORS.black,
  },

  inputText: {
    color: COLORS.black,
    marginLeft: SW(10),
    fontSize: scale(12),
    fontFamily: Fonts.Italic,
  },

  fieldsView: {
    width: SW(340),
    alignSelf: "center",
  },
  labelStyle: {
    fontFamily: Fonts.SemiBold,
    fontSize: SF(14),
    color: COLORS.text,
  },
  labelStyle2: {
    fontFamily: Fonts.Regular,
    fontSize: SF(14),
    color: COLORS.text,
  },
  input: {
    backgroundColor: COLORS.placeholder,
    borderColor: COLORS.placeholder,
    marginTop: verticalScale(5),
    paddingHorizontal: SW(15),
    alignItems: "center",
    borderRadius: 5,
    flexDirection: "row",
    height: SH(48),
  },
  calendarImage: {
    width: SH(19),
    height: SW(19),
  },
  textInputStyles: {
    width: SW(250),
    fontSize: scale(12),
    fontFamily: Fonts.Italic,
    marginLeft: SW(8),
    borderColor: COLORS.placeholder,
    height: SH(48),
  },
  textFieldStyle: {
    backgroundColor: COLORS.placeholder,
    borderColor: COLORS.transparent,
    marginTop: verticalScale(5),
    paddingVertical: verticalScale(10),
    paddingHorizontal: moderateScale(10),
    fontSize: scale(12),
    borderRadius: 5,
    fontFamily: Fonts.Italic,
    height: SH(48),
    color: COLORS.darkGrey,
  },
  IconTextFieldStyleView: {
    borderColor: COLORS.transparent,
    paddingHorizontal: moderateScale(10),
    borderRadius: 5,
    height: SH(48),
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.placeholder,
    marginTop: SH(5),
  },
  IconTextFieldStyle: {
    borderColor: COLORS.transparent,
    paddingVertical: verticalScale(10),
    paddingHorizontal: moderateScale(10),
    borderRadius: 5,
    height: SH(45),
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.placeholder,
    flex: 1,
    fontSize: scale(12),
    fontFamily: Fonts.Italic,
  },
  textFieldIcon: {
    height: SH(25),
    width: SW(25),
    tintColor: COLORS.primary,
  },

  modalView: {
    width: windowWidth * 0.8,
    height: SH(266),
    backgroundColor: COLORS.white,
    borderRadius: 15,
    alignSelf: "center",
    alignItems: "center",
  },
  logIn: {
    width: windowWidth * 0.8,
    backgroundColor: COLORS.sky,
    height: SH(46),
    borderRadius: 0,
    borderBottomLeftRadius: 15,
    borderBottomEndRadius: 15,
    borderColor: COLORS.sky,
  },
  done: {
    fontFamily: Fonts.MaisonMonoBold,
    color: COLORS.sky,
    fontSize: SF(24),
  },
  youVerified: {
    fontFamily: Fonts.Regular,
    color: COLORS.grey,
    fontSize: SF(14),
  },
  newPinSet: {
    fontFamily: Fonts.MaisonMonoBold,
    color: COLORS.darkGrey,
    fontSize: SF(18),
  },
  Verified: {
    width: SW(54),
    height: SH(54),
    resizeMode: "contain",
  },
  googlePlacesTextField: {
    backgroundColor: COLORS.placeholder,
    borderColor: COLORS.transparent,
    fontSize: scale(12),
    borderRadius: 5,
    fontFamily: Fonts.Italic,
    height: SH(48),
  },
  countryField: {
    backgroundColor: COLORS.placeholder,
    borderColor: COLORS.transparent,
    marginTop: verticalScale(10),
    paddingVertical: verticalScale(10),
    paddingHorizontal: moderateScale(10),
    fontSize: scale(12),
    borderRadius: 5,
    height: SH(48),
    color: COLORS.black,
  },
  dropDownIcon: {
    width: SW(5),
    height: SW(5),
    resizeMode: "contain",
    paddingRight: 30,
  },
  dropDownIcon2: {
    width: SW(5),
    height: SW(5),
    resizeMode: "contain",
    paddingRight: 30,
    transform: [{ rotate: "180deg" }],
  },
  dropdown: {
    width: SW(340),
    alignSelf: "center",
    backgroundColor: COLORS.placeholder,
    borderColor: COLORS.transparent,
    borderWidth: 0,
    // marginVertical: verticalScale(1),
    zIndex: Platform.OS === "ios" ? 100 : 0,
    fontFamily: Fonts.Italic,
  },
  containerStyle: {
    width: SW(340),
    borderWidth: 0,
    alignSelf: "center",
    marginTop: verticalScale(10),
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: SH(10),
  },
  maleCheckStyle: {
    flexDirection: "row",
    alignItems: "center",
  },
  maleCheckbox: {
    height: SW(25),
    width: SW(25),
    justifyContent: "center",
    alignItems: "center",
  },
  checkboxStyle: {
    width: SW(20),
    height: SW(20),
    resizeMode: "contain",
    alignSelf: "center",
  },
  femaleCheckStyle: {
    flexDirection: "row",
    marginLeft: SW(80),
  },
  checkboxLabel: {
    paddingLeft: SH(8),
    textAlignVertical: "center",
  },
  nextButton: {
    bottom: SH(40),
    alignSelf: "center",
  },
  placeholderTextStyle: {
    color: COLORS.placeholderText,
    fontFamily: Fonts.Italic,
  },
  labelTextStyle: {
    color: COLORS.dark_gray,
    fontSize: SF(16),
    fontFamily: Fonts.Regular,
  },
  maincontainer: {
    flexDirection: "row",
    backgroundColor: COLORS.white,
    alignItems: "center",
    height: SH(50),
    width: windowWidth,
    paddingHorizontal: moderateScale(15),
    marginRight: -20,
    justifyContent: "space-between",
    ...ShadowStyles.shadow,
  },
  headerIcon: {
    width: SW(28),
    height: SH(24),
    // marginHorizontal: moderateScale(5),
  },
  header: {
    color: COLORS.dark_gray,
    fontSize: SF(14),
    fontFamily: Fonts.SemiBold,
  },
  loginButton: {
    backgroundColor: COLORS.primary,
    borderColor: "transparent",
    height: SH(54),
    width: windowWidth * 0.92,
    alignSelf: "center",
  },
});
