export const NAVIGATION = {
  home: "Home",
  login: "Login",
  profile: "Profile",
  onboarding: "OnBoarding",
  splash: "Splash",
  login: "Login",
  mobileNumber: "MobileNumber",
  verify: "Verify",
  enterPin: "EnterPin",
  reEnterPin: "ReEnterPin",
  categories: "Categories",
  productInquiry: "ProductInquiry",
  sendInquiry: "SendInquiry",
  startOrder: "Start Order",
  delivery: "Delivery",
  reviewAndPayment: "ReviewAndPayment",
  addShippingAddress: "AddShippingAddress",
  addMoneyToWallet: "AddMoneyToWallet",
  paymentMethod: "PaymentMethod",
  addCreditCard: "AddCreditCard",
  newProducts: "NewProducts",
};
