export const TYPES = {
  CLEAR_STORE: "CLEAR_STORE",
  GLOBAL_RESET: "GLOBAL_RESET",

  GET_CATEGORY: "GET_CATEGORY",
  GET_CATEGORY_REQUEST: "GET_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_CATEGORY_SUCCESS",
  GET_CATEGORY_ERROR: "GET_CATEGORY_ERROR",

  GET_SERVICE_CATEGORY: "GET_SERVICE_CATEGORY",
  GET_SERVICE_CATEGORY_REQUEST: "GET_SERVICE_CATEGORY_REQUEST",
  GET_SERVICE_CATEGORY_SUCCESS: "GET_SERVICE_CATEGORY_SUCCESS",
  GET_SERVICE_CATEGORY_ERROR: "GET_SERVICE_CATEGORY_ERROR",

  GET_SUB_CATEGORY: "GET_SUB_CATEGORY",
  GET_SUB_CATEGORY_REQUEST: "GET_SUB_CATEGORY_REQUEST",
  GET_SUB_CATEGORY_SUCCESS: "GET_SUB_CATEGORY_SUCCESS",
  GET_SUB_CATEGORY_ERROR: "GET_SUB_CATEGORY_ERROR",
  GET_SUB_CATEGORY_RESET: "GET_SUB_CATEGORY_RESET",

  GET_BRANDS: "GET_BRANDS",
  GET_BRANDS_REQUEST: "GET_BRANDS_REQUEST",
  GET_BRANDS_SUCCESS: "GET_BRANDS_SUCCESS",
  GET_BRANDS_ERROR: "GET_BRANDS_ERROR",
  GET_BRANDS_RESET: "GET_BRANDS_RESET",

  GET_PRODUCT: "GET_CATEGORY",
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
  GET_PRODUCT_RESET: "GET_PRODUCT_RESET",

  GET_BANNER: "GET_BANNER",
  GET_BANNER_REQUEST: "GET_BANNER_REQUEST",
  GET_BANNER_SUCCESS: "GET_BANNER_SUCCESS",
  GET_BANNER_ERROR: "GET_BANNER_ERROR",

  GET_PRODUCT_DETAIL: "GET_PRODUCT_DETAIL",
  GET_PRODUCT_DETAIL_REQUEST: "GET_PRODUCT_DETAIL_REQUEST",
  GET_PRODUCT_DETAIL_SUCCESS: "GET_PRODUCT_DETAIL_SUCCESS",
  GET_PRODUCT_DETAIL_ERROR: "GET_PRODUCT_DETAIL_ERROR",
  GET_PRODUCT_DETAIL_RESET: "GET_PRODUCT_DETAIL_RESET",

  GET_TRENDING_PRODUCTS: "GET_TRENDING_PRODUCTS",
  GET_TRENDING_PRODUCTS_REQUEST: "GET_TRENDING_PRODUCTS_REQUEST",
  GET_TRENDING_PRODUCTS_SUCCESS: "GET_TRENDING_PRODUCTS_SUCCESS",
  GET_TRENDING_PRODUCTS_ERROR: "GET_TRENDING_PRODUCTS_ERROR",
  GET_TRENDING_PRODUCTS_RESET: "GET_TRENDING_PRODUCTS_RESET",

  GET_TRENDING_SELLERS: "GET_TRENDING_SELLERS",
  GET_TRENDING_SELLERS_REQUEST: "GET_TRENDING_SELLERS_REQUEST",
  GET_TRENDING_SELLERS_SUCCESS: "GET_TRENDING_SELLERS_SUCCESS",
  GET_TRENDING_SELLERS_ERROR: "GET_TRENDING_SELLERS_ERROR",

  GET_COUPONS: "GET_COUPONS",
  GET_COUPONS_REQUEST: "GET_COUPONS_REQUEST",
  GET_COUPONS_SUCCESS: "GET_COUPONS_SUCCESS",
  GET_COUPONS_ERROR: "GET_COUPONS_ERROR",

  ADD_COUPONS: "ADD_COUPONS",
  ADD_COUPONS_REQUEST: "ADD_COUPONS_REQUEST",
  ADD_COUPONS_SUCCESS: "ADD_COUPONS_SUCCESS",
  ADD_COUPONS_ERROR: "ADD_COUPONS_ERROR",

  SEND_OTP: "SEND_OTP",
  SEND_OTP_REQUEST: "SEND_OTP_REQUEST",
  SEND_OTP_SUCCESS: "SEND_OTP_SUCCESS",
  SEND_OTP_ERROR: "SEND_OTP_ERROR",

  SAVE_PHONE: "SAVE_PHONE",

  SAVE_OTP: "SAVE_OTP",

  LOGIN: "LOGIN",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",

  VERIFY_OTP: "VERIFY_OTP",
  VERIFY_OTP_REQUEST: "VERIFY_OTP_REQUEST",
  VERIFY_OTP_SUCCESS: "VERIFY_OTP_SUCCESS",
  VERIFY_OTP_ERROR: "VERIFY_OTP_ERROR",

  FORGOT_PIN: "FORGOT_PIN",
  FORGOT_PIN_REQUEST: "FORGOT_PIN_REQUEST",
  FORGOT_PIN_SUCCESS: "FORGOT_PIN_SUCCESS",
  FORGOT_PIN_ERROR: "FORGOT_PIN_ERROR",

  REGISTER_DATA: "REGISTER_DATA",
  REGISTER_DATA_REQUEST: "REGISTER_DATA_REQUEST",
  REGISTER_DATA_SUCCESS: "REGISTER_DATA_SUCCESS",
  REGISTER_DATA_ERROR: "REGISTER_DATA_ERROR",

  REGISTER: "REGISTER",
  REGISTER_REQUEST: "REGISTER_REQUEST",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",

  PERSONALINFORMATION: "PERSONALINFORMATION",
  PERSONALINFORMATION_REQUEST: "PERSONALINFORMATION_REQUEST",
  PERSONALINFORMATION_SUCCESS: "PERSONALINFORMATION_SUCCESS",
  PERSONALINFORMATION_ERROR: "PERSONALINFORMATION_ERROR",

  GET_COUNTRY_REQUEST: "GET_COUNTRY_REQUEST",
  GET_COUNTRY_SUCCESS: "GET_COUNTRY_SUCCESS",
  GET_COUNTRY_ERROR: "GET_COUNTRY_ERROR",

  GET_STATE_REQUEST: "GET_STATE_REQUEST",
  GET_STATE_SUCCESS: "GET_STATE_SUCCESS",
  GET_STATE_ERROR: "GET_STATE_ERROR",

  GET_CITIES_REQUEST: "GET_CITIES_REQUEST",
  GET_CITIES_SUCCESS: "GET_CITIES_SUCCESS",
  GET_CITIES_ERROR: "GET_CITIES_ERROR",

  AGE_VERIFIY: "AGE_VERIFIY",
  AGE_VERIFIY_REQUEST: "AGE_VERIFIY_REQUEST",
  AGE_VERIFIY_SUCCESS: "AGE_VERIFIY_SUCCESS",
  AGE_VERIFIY_ERROR: "AGE_VERIFIY_ERROR",

  GET_SUBJECT_REQUEST: "GET_SUBJECT_REQUEST",
  GET_SUBJECT_SUCCESS: "GET_SUBJECT_SUCCESS",
  GET_SUBJECT_ERROR: "GET_SUBJECT_ERROR",

  GET_USER_DETAILS_REQUEST: "GET_USER_DETAILS_REQUEST",
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_ERROR: "GET_USER_DETAILS_ERROR",

  GET_USER: "GET_USER",
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_ERROR",

  EDIT_PROFILE: "EDIT_PROFILE",
  EDIT_PROFILE_REQUEST: "EDIT_PROFILE_REQUEST",
  EDIT_PROFILE_SUCCESS: "EDIT_PROFILE_SUCCESS",
  EDIT_PROFILE_ERROR: "EDIT_PROFILE_ERROR",

  EMAIL_VERIFY_OTP: "EMAIL_VERIFY_OTP",
  EMAIL_VERIFY_OTP_REQUEST: "EMAIL_VERIFY_OTP_REQUEST",
  EMAIL_VERIFY_OTP_ERROR: "EMAIL_VERIFY_OTP_ERROR",
  EMAIL_VERIFY_OTP_SUCCESS: "EMAIL_VERIFY_OTP_SUCCESS",

  NEAR_ME_SELLERS: "NEAR_ME_SELLERS",
  NEAR_ME_SELLERS_SUCCESS: "NEAR_ME_SELLERS_SUCCESS",
  NEAR_ME_SELLERS_ERROR: "NEAR_ME_SELLERS_ERROR",
  NEAR_ME_SELLERS_REQUEST: "NEAR_ME_SELLERS_REQUEST",

  FAQ: "FAQ",
  FAQ_SUCCESS: "FAQ_SUCCESS",
  FAQ_ERROR: "FAQ_ERROR",
  FAQ_REQUEST: "FAQ_REQUEST",

  SETTINGS: "SETTINGS",
  SETTINGS_SUCCESS: "SETTINGS_SUCCESS",
  SETTINGS_ERROR: "SETTINGS_ERROR",
  SETTINGS_REQUEST: "SETTINGS_REQUEST",

  BIOMETRIC: "BIOMETRIC",
  BIOMETRIC_SUCCESS: "BIOMETRIC_SUCCESS",
  BIOMETRIC_ERROR: "BIOMETRIC_ERROR",
  BIOMETRIC_REQUEST: "BIOMETRIC_REQUEST",

  GET_SUPPORTLIST: "GET_SUPPORTLIST",
  GET_SUPPORTLIST_REQUEST: "GET_SUPPORTLIST_REQUEST",
  GET_SUPPORTLIST_SUCCESS: "GET_SUPPORTLIST_SUCCESS",
  GET_SUPPORTLIST_ERROR: "GET_SUPPORTLIST_ERROR",

  BUSINESS_TYPE_REQUEST: "BUSINESS_TYPE_REQUEST",
  BUSINESS_TYPE_SUCCESS: "BUSINESS_TYPE_SUCCESS",
  BUSINESS_TYPE_ERROR: "BUSINESS_TYPE_ERROR",

  NAICS_CODE_REQUEST: "NAICS_CODE_REQUEST",
  NAICS_CODE_SUCCESS: "NAICS_CODE_SUCCESS",
  NAICS_CODE_ERROR: "NAICS_CODE_ERROR",

  REQUEST_BUSINESS: "REQUEST_KYC",
  REQUEST_BUSINESS_REQUEST: "REQUEST_BUSINESS_REQUEST",
  REQUEST_BUSINESS_SUCCESS: "REQUEST_BUSINESS_SUCCESS",
  REQUEST_BUSINESS_ERROR: "REQUEST_BUSINESS_ERROR",

  CHECK_BUSINESS: "CHECK_KYC",
  CHECK_BUSINESS_REQUEST: "CHECK_BUSINESS_REQUEST",
  CHECK_BUSINESS_SUCCESS: "CHECK_BUSINESS_SUCCESS",
  CHECK_BUSINESS_ERROR: "CHECK_BUSINESS_ERROR",

  REQUEST_KYC: "REQUEST_KYC",
  REQUEST_KYC_REQUEST: "REQUEST_KYC_REQUEST",
  REQUEST_KYC_SUCCESS: "REQUEST_KYC_SUCCESS",
  REQUEST_KYC_ERROR: "REQUEST_KYC_ERROR",

  CHECK_KYC: "CHECK_KYC",
  CHECK_KYC_REQUEST: "CHECK_KYC_REQUEST",
  CHECK_KYC_SUCCESS: "CHECK_KYC_SUCCESS",
  CHECK_KYC_ERROR: "CHECK_KYC_ERROR",

  TRANSFER_MONEY: "TRANSFER_MONEY",
  TRANSFER_MONEY_REQUEST: "TRANSFER_MONEY_REQUEST",
  TRANSFER_MONEY_SUCCESS: "TRANSFER_MONEY_SUCCESS",
  TRANSFER_MONEY_ERROR: "TRANSFER_MONEY_ERROR",
  GET_DOCUMENT_TYPES_REQUEST: "GET_DOCUMENT_TYPES_REQUEST",
  GET_DOCUMENT_TYPES_SUCCESS: "GET_DOCUMENT_TYPES_SUCCESS",
  GET_DOCUMENT_TYPES_ERROR: "GET_DOCUMENT_TYPES_ERROR",

  GET_PLAID_TOKEN: "GET_PLAID_TOKEN",
  GET_PLAID_TOKEN_REQUEST: "GET_PLAID_TOKEN_REQUEST",
  GET_PLAID_TOKEN_SUCCESS: "GET_PLAID_TOKEN_SUCCESS",
  GET_PLAID_TOKEN_ERROR: "GET_PLAID_TOKEN_ERROR",

  LINK_BANK_ACCOUNT: "LINK_BANK_ACCOUNT",
  LINK_BANK_ACCOUNT_REQUEST: "LINK_BANK_ACCOUNT_REQUEST",
  LINK_BANK_ACCOUNT_SUCCESS: "LINK_BANK_ACCOUNT_SUCCESS",
  LINK_BANK_ACCOUNT_ERROR: "LINK_BANK_ACCOUNT_ERROR",

  GET_BANK_ACCOUNTS_REQUEST: "GET_BANK_ACCOUNTS_REQUEST",
  GET_BANK_ACCOUNTS_SUCCESS: "GET_BANK_ACCOUNTS_SUCCESS",
  GET_BANK_ACCOUNTS_ERROR: "GET_BANK_ACCOUNTS_ERROR",

  ADD_NEW_TICKET: "ADD_NEW_TICKET",
  ADD_NEW_TICKET_REQUEST: "ADD_NEW_TICKET_REQUEST",
  ADD_NEW_TICKET_SUCCESS: "ADD_NEW_TICKET_SUCCESS",
  ADD_NEW_TICKET_ERROR: "ADD_NEW_TICKET_ERROR",

  GET_PAYMENT_METHODS_REQUEST: "GET_PAYMENT_METHODS_REQUEST",
  GET_PAYMENT_METHODS_SUCCESS: "GET_PAYMENT_METHODS_SUCCESS",
  GET_PAYMENT_METHODS_ERROR: "GET_PAYMENT_METHODS_ERROR",

  BUSINESS_DOCUMENTS_UPLOAD: "BUSINESS_DOCUMENTS_UPLOAD",
  BUSINESS_DOCUMENTS_UPLOAD_REQUEST: "BUSINESS_DOCUMENTS_UPLOAD_REQUEST",
  BUSINESS_DOCUMENTS_UPLOAD_SUCCESS: "BUSINESS_DOCUMENTS_UPLOAD_SUCCESS",
  BUSINESS_DOCUMENTS_UPLOAD_ERROR: "BUSINESS_DOCUMENTS_UPLOAD_ERROR",

  BUSINESS_REGISTRATION: "BUSINESS_REGISTRATION",
  BUSINESS_REGISTRATION_REQUEST: "BUSINESS_REGISTRATION_REQUEST",
  BUSINESS_REGISTRATION_SUCCESS: "BUSINESS_REGISTRATION_SUCCESS",
  BUSINESS_REGISTRATION_ERROR: "BUSINESS_REGISTRATION_ERROR",

  DOCUMENTS_UPLOAD: "DOCUMENTS_UPLOAD",
  DOCUMENTS_UPLOAD_REQUEST: "DOCUMENTS_UPLOAD_REQUEST",
  DOCUMENTS_UPLOAD_SUCCESS: "DOCUMENTS_UPLOAD_SUCCESS",
  DOCUMENTS_UPLOAD_ERROR: "DOCUMENTS_UPLOAD_ERROR",

  GET_WALLET_USER: "GET_WALLET_USER",
  GET_WALLET_USER_REQUEST: "GET_WALLET_USER_REQUEST",
  GET_WALLET_USER_SUCCESS: "GET_WALLET_USER_SUCCESS",
  GET_WALLET_USER_ERROR: "GET_WALLET_USER_ERROR",

  CREATE_WALLET_USER: "CREATE_WALLET_USER",
  CREATE_WALLET_USER_REQUEST: "CREATE_WALLET_USER_REQUEST",
  CREATE_WALLET_USER_SUCCESS: "CREATE_WALLET_USER_SUCCESS",
  CREATE_WALLET_USER_ERROR: "CREATE_WALLET_USER_ERROR",

  ADD_BALANCE: "ADD_BALANCE",
  ADD_BALANCE_REQUEST: "ADD_BALANCE_REQUEST",
  ADD_BALANCE_SUCCESS: "ADD_BALANCE_SUCCESS",
  ADD_BALANCE_ERROR: "ADD_BALANCE_ERROR",

  CHECK_BALANCE_REQUEST: "CHECK_BALANCE_REQUEST",
  CHECK_BALANCE_SUCCESS: "CHECK_BALANCE_SUCCESS",
  CHECK_BALANCE_ERROR: "CHECK_BALANCE_ERROR",

  REDEEM_MONEY: "REDEEM_MONEY",
  REDEEM_MONEY_REQUEST: "REDEEM_MONEY_REQUEST",
  REDEEM_MONEY_SUCCESS: "REDEEM_MONEY_SUCCESS",
  REDEEM_MONEY_ERROR: "REDEEM_MONEY_ERROR",

  GET_WALLET_BALANCE: "GET_WALLET_BALANCE",
  GET_WALLET_BALANCE_REQUEST: "GET_WALLET_BALANCE_REQUEST",
  GET_WALLET_BALANCE_SUCCESS: "GET_WALLET_BALANCE_SUCCESS",
  GET_WALLET_BALANCE_ERROR: "GET_WALLET_BALANCE_ERROR",

  GET_TRANSACTIONS_REQUEST: "GET_TRANSACTIONS_REQUEST",
  GET_TRANSACTIONS_SUCCESS: "GET_TRANSACTIONS_SUCCESS",
  GET_TRANSACTIONS_ERROR: "GET_TRANSACTIONS_ERROR",

  GET_REQUEST_TRANSACTIONS_REQUEST: "GET_REQUEST_TRANSACTIONS_REQUEST",
  GET_REQUEST_TRANSACTIONS_SUCCESS: "GET_REQUEST_TRANSACTIONS_SUCCESS",
  GET_REQUEST_TRANSACTIONS_ERROR: "GET_REQUEST_TRANSACTIONS_ERROR",

  GET_ALL_RECEIVERS_REQUEST: "GET_ALL_RECEIVERS_REQUEST",
  GET_ALL_RECEIVERS_SUCCESS: "GET_ALL_RECEIVERS_SUCCESS",
  GET_ALL_RECEIVERS_ERROR: "GET_ALL_RECEIVERS_ERROR",

  REQUEST_MONEY: "REQUEST_MONEY",
  REQUEST_MONEY_REQUEST: "REQUEST_MONEY_REQUEST",
  REQUEST_MONEY_SUCCESS: "REQUEST_MONEY_SUCCESS",
  REQUEST_MONEY_ERROR: "REQUEST_MONEY_ERROR",

  REMOVE_BANK_ACCOUNT: "REMOVE_BANK_ACCOUNT",
  REMOVE_BANK_ACCOUNT_REQUEST: "REMOVE_BANK_ACCOUNT_REQUEST",
  REMOVE_BANK_ACCOUNT_SUCCESS: "REMOVE_BANK_ACCOUNT_SUCCESS",
  REMOVE_BANK_ACCOUNT_ERROR: "REMOVE_BANK_ACCOUNT_ERROR",

  ACCEPT_MONEY: "ACCEPT_MONEY",
  ACCEPT_MONEY_REQUEST: "ACCEPT_MONEY_REQUEST",
  ACCEPT_MONEY_SUCCESS: "ACCEPT_MONEY_SUCCESS",
  ACCEPT_MONEY_ERROR: "ACCEPT_MONEY_ERROR",

  REJECT_MONEY: "REJECT_MONEY",
  REJECT_MONEY_REQUEST: "REJECT_MONEY_REQUEST",
  REJECT_MONEY_SUCCESS: "REJECT_MONEY_SUCCESS",
  REJECT_MONEY_ERROR: "REJECT_MONEY_ERROR",

  SCAN_QR_CODE: "SCAN_QR_CODE",
  SCAN_QR_CODE_REQUEST: "SCAN_QR_CODE_REQUEST",
  SCAN_QR_CODE_SUCCESS: "SCAN_QR_CODE_SUCCESS",
  SCAN_QR_CODE_ERROR: "SCAN_QR_CODE_ERROR",

  CREATE_CART: "CREATE_CART",
  CREATE_CART_REQUEST: "CREATE_CART_REQUEST",
  CREATE_CART_SUCCESS: "CREATE_CART_SUCCESS",
  CREATE_CART_ERROR: "CREATE_CART_ERROR",

  GET_CART: "GET_CART",
  GET_CART_REQUEST: "GET_CART_REQUEST",
  GET_CART_SUCCESS: "GET_CART_SUCCESS",
  GET_CART_ERROR: "GET_CART_ERROR",
  GET_CART_RESET: "GET_CART_RESET",

  GET_SHIPPING_SERVICES: "GET_SHIPPING_SERVICES",
  GET_SHIPPING_SERVICES_REQUEST: "GET_SHIPPING_SERVICES_REQUEST",
  GET_SHIPPING_SERVICES_SUCCESS: "GET_SHIPPING_SERVICES_SUCCESS",
  GET_SHIPPING_SERVICES_ERROR: "GET_SHIPPING_SERVICES_ERROR",
  GET_SHIPPING_SERVICES_RESET: "GET_SHIPPING_SERVICES_RESET",

  USER_LOCATION: "USER_LOCATION",
  USER_LOCATION_REQUEST: "USER_LOCATION_REQUEST",
  USER_LOCATION_SUCCESS: "USER_LOCATION_SUCCESS",
  USER_LOCATION_ERROR: "USER_LOCATION_ERROR",

  // GET_USER_LOCATION: "GET_USER_LOCATION",
  // GET_USER_LOCATION_REQUEST: "GET_USER_LOCATION_REQUEST",
  // GET_USER_LOCATION_SUCCESS: "GET_USER_LOCATION_SUCCESS",
  // GET_USER_LOCATION_ERROR: "GET_USER_LOCATION_ERROR",

  SAVE_ADDRESS: "SAVE_ADDRESS",
  SAVE_ADDRESS_REQUEST: "SAVE_ADDRESS_REQUEST",
  SAVE_ADDRESS_SUCCESS: "SAVE_ADDRESS_SUCCESS",
  SAVE_ADDRESS_ERROR: "SAVE_ADDRESS_ERROR",

  UPDATE_USER_LOCATION: "UPDATE_USER_LOCATION",
  UPDATE_USER_LOCATION_REQUEST: "UPDATE_USER_LOCATION_REQUEST",
  UPDATE_USER_LOCATION_SUCCESS: "UPDATE_USER_LOCATION_SUCCESS",
  UPDATE_USER_LOCATION_ERROR: "UPDATE_USER_LOCATION_ERROR",

  SUPPLY_VARIANT: "SUPPLY_VARIANT",
  SUPPLY_VARIANT_REQUEST: "SUPPLY_VARIANT_REQUEST",
  SUPPLY_VARIANT_SUCCESS: "SUPPLY_VARIANT_SUCCESS",
  SUPPLY_VARIANT_ERROR: "SUPPLY_VARIANT_ERROR",
  SUPPLY_VARIANT_RESET: "SUPPLY_VARIANT_RESET",

  CATEGORY_WITH_PRODUCT: "CATEGORY_WITH_PRODUCT",
  CATEGORY_WITH_PRODUCT_REQUEST: "CATEGORY_WITH_PRODUCT_REQUEST",
  CATEGORY_WITH_PRODUCT_SUCCESS: "CATEGORY_WITH_PRODUCT_SUCCESS",
  CATEGORY_WITH_PRODUCT_ERROR: "CATEGORY_WITH_PRODUCT_ERROR",
  CATEGORY_WITH_PRODUCT_RESET: "CATEGORY_WITH_PRODUCT_RESET",
};
