export const TYPES = {
  CLEAR_STORE: "CLEAR_STORE",
  GET_CATEGORY: "GET_CATEGORY",
  GET_CATEGORY_REQUEST: "GET_SUB_CATEGORY_REQUEST",
  GET_CATEGORY_SUCCESS: "GET_SUB_CATEGORY_SUCCESS",
  GET_CATEGORY_ERROR: "GET_SUB_CATEGORY_ERROR",

  GET_PRODUCT: "GET_CATEGORY",
  GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
  GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
  GET_PRODUCT_ERROR: "GET_PRODUCT_ERROR",
};
