export const en = {
  validation: {
    error: "Error",
    alert: "Alert",
    enterPhone: "Please enter phone number",
    enterCode: "Please enter phone code",
    enterOtp: "Please enter otp",
    validPhone: "Please enter valid phone number",
    phoneLength: "Phone number must be at least 10 characters long",
    enterUserName: "Please enter username",
    validUserName: "Please enter valid username",
    firstName: "Please enter first name",
    validFirstName: "Please enter valid first name",
    lastNameerror: "Please enter last name",
    validlastName: "Please enter valid last name",
    enterPin: "Please enter pin",
    enter4digit: "Please enter 4 digit pin",
    conformPin: "Please enter confirm pin",
    pinNotMatch: "Pin and Confirm Pin should be same",
    enterDate: "Please select date of birth",
    enterSsn: "Please enter SSN",
    invalidSSN: "Please enter only digits in SSN field",
    selectGender: "Please select gender",
    enterStret: "Please enter street address",
    enterapartment: "Please enter apartment",
    selectCity: "Please enter city",
    selectState: "Please enter state",
    enterZip: "Please enter zip code",
    selectIdentity: "Please select identity type",
    country: "Please enter country",
    subject: "Please select subject",
    enterDescription: "Please enter description",
    uploadDocuemnt: "Please upload document",
    enterEmail: "Please enter email",
    profileimage: "Please select profile image",
    validEmail: "Please enter valid email",
    enterAmount: "Please enter amount",
    emptyCardNumber: "Please enter card number",
    emptyExpiryDate: "Please enter expiry date",
    emptyCVV: "Please enter CVV",
    emptyCardHolderName: "Please enter card holder name",
    invalidCardHolderName: "Please enter valid card holder name",
    invalidCvv: "Please enter valid CVV",
    invalidCardNumber: "Please enter valid card number",
    invalidDate: "Please enter valid expiry date",
    invalidOtp: "Please enter valid OTP",
    emptyEmail: "Please enter email address",
    invalidEmail: "Please enter valid email address",
    selectType: "Please select a type",
    token: "Login to report a issue",
    enterAmount: "Please enter valid amount",
    selectBank: "Please select a bank account",
    emptyBusinessName: "Please enter a business name",
    invalidCardNumber: "Please enter valid card number",
    emptyCardHolderName: "Please enter card holder name",
    invalidBusinessName: "Please enter a valid business name",
    invalidCardHolderName: "Please enter valid card holder name",
    emptyEmployerNo: "Please enter Employer Identification Number",
    invalidBusinessWebsite: "Please enter a valid business website",
    invalidEmployerNo: "Please enter valid Employer Identification Number",
  },
  personalInformation: {
    email: "Enter you email address",
    userName: "Enter your username",
    firstName: "Enter your first name",
    lastName: "Enter your last name",
    enterPin: "Set your pin",
    reEnterPin: "Re-enter your pin",
    ssn: "SSN",
    placeholder: "YYYY / MM / DD",
    gender: "Gender",
    type: "Type",
    male: "Male",
    female: "Female",
    individual: "Individual",
    business: "Business",
    currentAddress: "Current Address",
    appart: "Apt.",
    city: "City",
    state: "State",
    zip: "Zip Code",
    country: "Country",
    header: "Information for kyc",
    title: "Personal Information",
    labelDob: "Date of birthday (month / day / year)",
    emailVerification: "Email verification",
    emailAddress: "Email Address",
  },
  buttonText: {
    next: "Next",
    send: "Send",
    add: "Add",
    sendOffer: "SendOffer",
    edit: "Edit",
    save: "Save",
    addNewAddressNo: "Add new address ",
    addNewAddress: "Add new address",
    skip: "Skip",
    submit: "Submit",
    selectAddress: "Select Address",
  },

  verify: {
    error: "Error",
  },
  common: {
    loading: "Loading",
    connectionError: "Connection error",
    noDataFound: "No data found",
  },
  home: {
    header: "Home",
    message: "Welcome",
    variant: "App variant: ",
    nearMe: "Near me",
  },
  login: {
    username: "Username",
    usernameHint: "Enter your username",
    button: "Login",
    password: "Password",
    passwordHint: "Enter your password",
    invalidCredentials: "Invalid Username/Password",
    scanbutton: "Login with biometrics",
    pinbutton: "Login with pin",
  },
  profile: {
    header: "Profile",
    logout: "Logout",
    message: "This screen has the iOS native large header.",
    myJobr: "My Jobr",
    username: "Schaden-Beier",
    address: "4554 Adamsville Road, Mission, TX 78572",
    manufacturer: "Manufacturer",
    myPurchase: "My Purchase",
    requestQuotation: "Request for Quotation",
    inquiries: "Inquiries",
    myCoupons: "My Coupons",
    favouriteList: "Favourite List",
    searchingPreference: "Searching Preference",
    shippingAddress: "Shipping Address",
    jbrWallet: "JBR Wallet",
    paymentMethods: "Payment Methods",
    businessCard: "Business Cards",
    myCatalogs: "My Catalogs",
    helpCenter: "Help Center",
    settings: "Settings",
    howCanWeHelp: "How can we help you?",
  },

  splash: {
    register: "Register",
    signIn: "Sign in",
  },
  auth: {
    tellBusiness: "Tell us about your business",
    whichOne: "Which of the following best describes your business?",
    next: "Next",
    enterPin: "Enter your PIN for login",
    forgotPin: "Forgot PIN?",
    enterMobile: "Continue with your phone number",
    pleaseEnterMobile: "Please enter your number to phone number",
    mobilePlaceholder: "815-288-0329",
    continue: "Continue",
    verifyNumber: "Verify your",
    phoneNumber: "phone number",
    enterOtp: "Enter OTP code here",
    dontReceiveCode: "Didn’t receive Code?",
    resend: " Resend",
    setPin: "Set up PIN",
    cancel: "Cancel",
    enterYourPin: "Enter your PIN",
    logIn: "Log in",
    reEnterPin: "Re-enter your PIN",
    done: "Done!",
    youVerified: "You are verified!",
    newPinSet: "Your new pin is set now",
  },
  search: {
    search: "Search here",
  },

  categories: {
    addtopCat: "Add your top categories",
    letsHelp: "Lets help you find what you need.",
    seatchHere: "Search here",
    suggestion: "Suggestions",
  },

  productInquiry: {
    aboutCompany: "About Company",
    follow: "Follow",
    followed: "Followed",
    visitStore: "Visit Store",
    productDetails: "Product Details",
    recomended: "Recomended products",
    startOrder: "Start Order",
    sendInquiry: "Send Inquiry",
    addToBag: "Add to Bag",
    buyNow: "Buy Now",
    viewAll: "View all",
    sleeveLength: "Sleeve Length",
    type: "Type",
    lining: "Lining Fabric",
    print: "Print or Pattern Type",
    occasion: "Occasion",
    recomended: "Recommended Products",
    chatNow: "Chat Now",
    estimated: "Estimated arrival within 7 business days with JOBR shipping",
    productDetailText:
      "A popular type of cigarette from the Marlboro brand due to its smooth flavour and it being mid-priced",
  },
  sendInquiry: {
    quantity: "Quantity",
    units: "Units of Measure",
    aboutCompany: "About Company",
    follow: "Follow",
    visitStore: "Visit Store",
    addHere: "Add you files here",
  },
  startOrder: {
    checkout: "Checkout",
    delivery: "Delivery",
    startOrder: "Variations",
    fedEx: "Fedex Express shipping",
    ups: "UPS Priority shipping",
    dhl: "DHL Standard shipping",
    jobr: "JOBR Standard shipping",
    done: "Done",
    itemsValue: "Items value",
  },
  delivery: {
    reviewAndPayment: "Review & Payment",
    placeOrderMissingAddress: "Place Order (Missing address)",
    fedEx: "Fedex Express shipping",
    ups: "UPS Priority shipping",
    dhl: "DHL Standard shipping",
    jobr: "JOBR Standard shipping",
  },
  AddShippingAddress: {
    currentAddress: "Current Address",
    addShippingAddress: "Shippping Address",
    save: "Save",
    firstName: "First Name",
    lastname: "Last Name",
    address1: "Address line 1",
    address2: "Address line 2",
    streets: "Streets, building",
    apartment: "Apartment optional",
    zipcode: "Zip Code",
    city: "City",
    savedefault: "Save as defult shippng address",
    enterFirstName: "Enter your first name",
    enterLastName: "Enter your last name",
    note: "Note",
    addAddress: "Add Address",
  },
  wallet: {
    agreement:
      "If you wish to purchase any product or service made available through Service (“Purchase”), you may be asked to supply certain information relevant to your Purchase including but not limited to, your credit or debit card number, the expiration date of your card, your billing address, and your shipping information.",
    wallet: "Wallet",
    close: "Close",
    useCoin:
      "Use coins to buy products from any listed stores and support/ tip to your rider",
    getJbr: "Get 15.00 JBR for every referral",
  },
  paymentMethod: {
    paymentMethod: "Payment methods",
    paynow: "Pay Now",
    addCreditCard: "Add Credit Card",
    applePay: "Apple Pay",
    addDebitCard: "Add Debit Card",
    connectBank: "Connect your bank account",
    availableBalance: "Available Balance",
    default: "Default",
  },
  addCreditCard: {
    addCreditCard: "Add a credit card",
    cardNumber: "Card Number",
    expiry: "Expiry",
    cvv: "CVV",
    cardHolderName: "Card Holder Name",
    sameShippingAddress: "Shipping address as same billing address",
    saveCard: "Save this card for a faster checkout",
    agreement:
      "By saving your card you grant us your consent to stor your payment method for future order. You can withdraw anytime.",
    monthYear: "mm/yy",
    cvvNo: "123",
    yes: "Yes",
    no: "No",
    addCard: "Add Card",
  },
  products: {
    newProducts: "New Products",
    seeAll: "See all",
    recomendedWholesalers: "Recomended Wholesalers",
  },
  newProducts: {
    newProducts: "New Products",
    filter: "Filter",
    subText:
      "It is a long established fact that a reader will be distracted by the readable content.",
  },
  business: {
    topManufactor: "Top-rank Manufacturers",
    seeAll: "See all",
    bestSellers: "Best Sellers",
    shoeMan: "Shoe man",
    electronics: "Electronics",
    topCategoryManufacturer: "Top Category Manufacturers",
    womenFashion: "Women's fashion",
    menFashion: "Men's fashion",
    phones: "Phones & Telecommunications",
    jeans: "Jeans",
    manufacturers: "Manufacturers",
    orders: "Orders",
    trending: "Trending",
    tobacco: "Tobacco",
    apparel: "Apparel",
    getSamples: "Get Samples",
    searchInStore: "Search in this store",
    filter: "Filter",
    searchHere: "Search here",
    carton: "Carton",
  },
  topRankingManufacturers: {
    topManufacturers: "Top Manufacturers",
    topRankingManufacturers: "Top-Ranking \nManufacturers",
    subText:
      "It is a long established fact that a reader will be distracted by the readable content.",
  },
  businessProfile: {
    businessDetails: "Business Details",
    subTitle: "colored cozy short cardigan",
    text: "Mauris eget blandit ex. Ut facilisis, lacus a faucibus finibus, nisi nisl pharetra enim, id fringilla ",
    companyReview: "Company Review",
    certification: "Certification",
    allvideos: "All videos",
    profile: "Profile",
    products: "Products",
    home: "Home",
    madeWell: "Made well",
    moq: "MOQ: 10",
    basicInformaion: "Basic Inforamation",
    bottomSheetText:
      "Shenzhen Poofect Technology Co., Ltd specializes in exporting Various consumer electronics productsOur products are mainly exported to the USA, Canada, Mexico, South America, Australia, New Zealand, as well as Southeast Asia. Our company's operating purpose is  top quality, and excellent servese PFCT people have been committed to offering our customers quality products and enthusiastic service to work hand in hand with them",
    overview: "Overview",
    yearestablished: "Year established",
    businessType: "Business type",
    country: "Country / Region",
    mainProducts: "Main products",
    revenue: "Total Annual Revenue",
    mainMarkets: "Main Markets",
    patents: "Patents(4)",
    productCertification: "Product Certifications(1)",
    productionEquipment: "Production Equipment",
    productionCertification: "Production Certification",
    factoryInspection: "Factory inspection reports",
    mainMarketDetail:
      "North America 30.00% \nSouth America 30.00% \nOceania 10.00%",
    verySatisfied: "Very Satisfied",
    reviews: "21 Reviews",
    suplierService: "Supplier Service",
    onTimeShipment: "On-time Shipment",
    productQuality: "Product Quality",
    customerReview:
      "Thank you for your help and quick delivery which enable our customer to meet his deadline – excellent service.",
    purchasedProducts: "Purchaced Products",
    itemNo: "300 (MOQ)",
  },
  reviewAndPayment: {
    deliveryTime: "Delivery Time",
    estimatedDelivery: "Estimated Delivery",
    addShippingAddress: "Add Shipping Address",
    days: "3-5 Days",
    workingdays: "3-5 working days",
    orderDetails: "Order Details",
    byCompleting: "By completing this order, I agree to all",
    terms: "terms & conditions",
  },
  userInformation: {
    back: "Back",
    personalInfo: "Personal Information",
    name: "Name",
    email: "Email address",
    phoneNumber: "Phone number",
    ssn: "SSN",
    dob: "Date of Birth",
    companyInfo: "Company Information",
    companyName: "Company Name",
    businessType: "Business Type",
    jobFunction: "Job Function",
    jobLevel: "Job Level",
    officeAddress: "Office Address",
    asv: "Annual Sourcing Value (USD)",
    sellingChannel: "Selling Channel",
    label: "Label",
    save: "Save",
  },
  qrCode: {
    scan: "Scan QR Code to pay or send money faster",
    share: "Share QR code",
    download: "Download QR Code",
  },
  settings: {
    shipTo: "Ship To",
    notifications: "Notifications",
    faceId: "Face ID & PIN",
    aboutUs: "About Us",
    contactUs: "Contact Us",
    privacyPolicy: "Privacy Policy",
    cookiePolicy: "Cookies Policy",
    terms: "Terms & Conditions",
    rateApp: "Rate the App",
    clearCache: "Clear app cache",
    usa: "United States of America",
    state: "State",
    city: "City",
    addLocations: "Add Locations",
    addShippingLocation: "Add a Shipping Location",
    saveDefault: "Save as default shipping address",
    country: "Country",
    add: "Add",
    canada: "Canada",
    mexico: "Mexico",
    next: "Next",
    notificationSetting: "Notification setting",
  },

  aboutUs: {
    jobr: "JOBR LLC.",
    paragraph1:
      "If your company has an interesting and intellectual history, you might consider creating a company profile like Wales Bonner’s. The profile reads like an essay from the very first line Informed by broad research encompassing critical theory, musical composition literature and history WALES BONNER embraces a multiplicity of perspectives proposing a distinct notion of luxuryvia a hybrid of European and Afro Atlantic approaches.",

    paragraph2:
      "After sharing the brand’s intellectual background it describes the owner’s journey in building the company, starting from the time she was a college student. With a good balance of image and text, the timeline serves as a reminder of Wales Bonners stability and growth.",
  },
  contactUs: {
    jobr: "JOBR LLC.",
    email: "Email address",
    phoneNumber: "Phone number",
    mail: "flowers@gmail.com",
  },
  privacyPolicy: {
    privacyPolicy: "Privacy Policy",
    welcome: "Welcome to JOBR !",
    para1:
      "You will need to fill out a form in the next step. Please read the instructions below to complete the form correctly",
    para2:
      "These terms and conditions outline the rules and regulations for the use of Company Name's Website, located at Website.com.",
    para3:
      "By accessing this website we assume you accept these terms and conditions. Do not continue to use Website Name if you do not agree to take all of the terms and conditions stated on this page.",
    para4:
      "The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: “Client”, “You” and “Your” refers to you, the person log on this website and compliant to the Company's terms and conditions. “The Company”, “Ourselves”, “We”, “Our” and “Us”, refers to our Company. “Party”, “Parties”, or “Us”, refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client's needs in respect of provision of the Company's stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.",
    cookies: "Cookies",
    para5:
      "We employ the use of cookies. By accessing Website Name, you agreed to use cookies in agreement with the Company Name's Privacy Policy.",
    para6:
      "Most interactive websites use cookies to let us retrieve the user's details for each visit. Cookies are used by our website to enable the functionality of certain areas to make it easier for people visiting our website. Some of our affiliate/advertising partners may also use cookies.",
    licenses: "License",
    para7:
      "Unless otherwise stated, Company Name and/or its licensors own the intellectual property rights for all material on Website Name. All intellectual property rights are reserved. You may access this from Website Name for your own personal use subjected to restrictions set in these terms and conditions.",
    youMustNot: "You must not",
    para8:
      "Republish material from Website Name. \nSell, rent or sub-license material from Website Name. \nReproduce, duplicate or copy material from Website Name. \nRedistribute content from Website Name. \nThis Agreement shall begin on the date hereof.",
    para9:
      "Parts of this website offer an opportunity for users to post and exchange opinions and information in certain areas of the website. Company Name does not filter, edit, publish or review Comments prior to their presence on the website. Comments do not reflect the views and opinions of Company Name,its agents and/or affiliates. Comments reflect the views and opinions of the person who post their views and opinions. To the extent permitted by applicable laws, Company Name shall not be liable for the Comments or for any liability, damages or expenses caused and/or suffered as a result of any use of and/or posting of and/or appearance of the Comments on this website.",
    para10:
      "Company Name reserves the right to monitor all Comments and to remove any Comments which can be considered inappropriate, offensive or causes breach of these Terms and Conditions.",
    yourWarrant: "You warrant and represent that:",
    para11:
      "You are entitled to post the Comments on our website and have all necessary licenses and consents to do so. \nThe Comments do not invade any intellectual property right, including without limitation copyright, patent or trademark of any third party. \nThe Comments do not contain any defamatory, libelous, offensive, indecent or otherwise unlawful material which is an invasion of privacy. \nThe Comments will not be used to solicit or promote business or custom or present commercial activities or unlawful activity. \nYou hereby grant Company Name a non-exclusive license to use, reproduce, edit and authorize others to use, reproduce and edit any of your Comments in any and all forms, formats or media.",
  },
  coupons: {
    coupons: "Coupons",
    addCoupon: "Add Coupon",
    welcomeCoupon: "Welcome Coupon",
    minimum: "minimum",
    valid: "Valid until",
    tc: "T&C",
    current: "Current",
    past: "Past",
    couponCode: "Coupon Code",
    notActive: "Not Active Coupon",
  },
  chatting: {
    chat: "Chat",
    photo: "Photo",
    quickMessage: "Quick Messages",
    videoCall: "Video Call",
    file: "File",
    businessCard: "Business Card",
    latestPrice: "Latest Price",
    voiceMessages: "Voice Messages",
    translator: "Translator",
    sendCatalogues: "Send Catalogue",
    shippingAddress: "Shipping Address",
    directOffer: "Direct Offer",
    takephoto: "Take a Photo",
    sendLocalPhoto: "Send Local Photo",
  },
  quickReplies: {
    bestOffer: "Hi, What’s the best price you can offer?",
  },
  videoCall: {
    notOnline:
      "We are not online for instant video calls. Please make a schedule for a video call. Our representative will join you at the right time",
    schedule: "Schedule",
    chooseTime: "Please choose a time below",
    fifteenMin:
      "It would be 15 minutes call with Yiwu Leqi E-Commerce Firm reprentative",
  },
  files: {
    localFiles: "Send local files",
  },
  cardDetails: {
    send: "Send",
  },
  voiceMessage: {
    hold: "Hold to talk",
  },
  chatShippingAddress: {
    addAddress: "Add Address",
  },

  translation: {
    longPress: "Long press translation setting",
    autoDetect: "Auto-detect",
    outGoingMessage: "Translate outgoing message",
  },

  makeAnOffer: {
    makeAnOffer: "Make an offer",
    selectCategory: "Select Category",
    selectSubCategory: "Select Sub Category",
    selectproduct: "Select Product",
    selectBrand: "Select Brand",
    brand: "Brand:",
    subCategory: "Sub-Category:",
    category: "Category:",
    selectedProduct: "Selected Product:",
    productName: "Product Name:",
  },
  sendAnOffer: {
    offering: "Offering",
    currentPrice: "Current Price",
    offeringPrice: "Offering Price",
    minimunOrder: "Minimun Order",
    carton: "Carton",
    offerValidity: "Offer Validity",
    selectDate: "Select Date",
    datePlaceholder: "YYYY / MM / DD",
  },
  notifications: {
    allowNoti: "Allow Notification",
    allowNotiPopup: "Allow Notification popup",
    chatMessages: "Chat Messages",
    promotions: "Promotions",
    orders: "Orders",
    feeds: "Feeds",
    rqf: "RQF",
  },
  faceId: {
    enable: "Enable",
    faceId: "Biometrics",
    pin: "Pin",
    text: "It is a long established fact that a reader will be distracted by the readable content.",
    setupFaceId: "Set up Face ID",
    setupPin: "Set up PIN",
  },
  jbrWallet: {
    availableBalance: "Available Balance",
    JBR: "JBR",
    buyingCapacity: "Buying capacity",
    brands: "Brands",
    purchases: "Purchases",
    earn: "Earn",
    transactionHistory: "Transaction history",
    buy: "Buy",
    added: "Added",
    earnRef: "Earn_ref",
    jbrAdded: "JBR added",
    purcased: "Purchased",
    products: "Products",
    manfacturer: "Manfacturers",
  },
  searchingPreferance: {
    yourBusiness: "Your Business:",
    onlineStore: "Online Store",
    personalizeBusiness: "Personalize your business",
    tellus: "Tell us about your business",
    decribes: "Which of the following best describes your business?",
    onlineStore: "Online Store",
    manufacturer: "Manufacturer",
    retailer: "Retailer",
    wholesaler: "Wholesaller/distro",
    other: "Other",
    letsHelp: "Lets help you find what you need.",
    addCategories: "Add you top categories",
  },
  addresses: {
    addresses: "Addresses",
    home: "Home",
    work: "Work",
    addressDetails: "Address details",
    addLabel: "Add label",
    billing: "Billing",
    other: "Other",
    apartment: "Apartment",
    floor: "Floor or Apt No (Optional)",
  },
  address: {
    button: "Save",
    detail: "Address details",
    apt: "Apartment",
    addressLine1Hint: "House / Flat / Block",
    addressLine2Hint: "Apartment / Road / Area(Optional)",
    floor: "Floor or Apr No(Optional)",
    label: "Add label",
    home: "Home",
    work: "Work",
    billing: "Billing",
    other: "Other",
    add1: "Address line 1",
    add2: "Address line 2",
    zip: "Zip code",
    city: "City",
    note: "Note",
    cityNm: "Miami",
    code: "12345",
    aptOp: "Apartment optional",
    street: "Streets, building",
    address: "Add Address",
    header: "Addresses",
  },
  myPurchase: {
    myPurchase: "My Purchase",
    orderDetails: "Order Details",
    pending: "Pending",
    toBeConfirmed: "To be Confirmed",
    paid: "Paid",
    pendingQuote: "Pending Quote",
    quote:
      "This order will autometically be cancled if the manufactured does not provide a shipping cost",
    trackOrder: "Track your order",
  },
  trackOrder: {
    trackYourOrder: "Track your order",
    orderStatus: "Order status",
    preparingYourOrder: "Preparing your order",
    verifyCode: "Verify code",
    delivery: "Delivery",
    withTenMin: "within 10 minutes",
    inWarehouse: "In Warehouse",
    productPickup: "Product Pickup by DHL",
    pickedByDhl: "Picked by DHL",
    orderProcessing: "Order Processing",
    madepayment: "Made Payment",
    map: "Map",
    order: "Order",
    rateYourExperience: "Rate Your Experience",
    areYou: "Are you satisfy with delivery service?",
    driver: "Driver",
    shop: "Shop",
    overallService: "Overall service",
    fiveStar: "5 star",
    rude: "Delivery man was rude",
    goodBehavior: "Good behavior",
    speed: "Speed and Efficiency",
    experienced: "Experienced",
    writeAdditional: "Write your additional feedback",
  },
  helpCenter: {
    mySupportRequest: "My support request",
    pastorders: "Past orders",
    myAccount: "My account",
    reportIssue: "Report other issue",
    faq: "FAQ",
    pending: "Pending",
    mySupport: "My support",
    support: "Support",
    subject: "Subject",
    paymentIssue: "Payment issue",
    lastRespond: "Last Respond",
    issueMessage:
      "Praesent a aliquam diam. Nullam nec feugiat turpis. Vestibulum fermentum in turpis et gravida. Phasellus feugiat ligula ut erat sodales.",
    completed: "Completed",
    openNewTicket: "Open new ticket",
    ourGateway:
      "Our gateway is routed directly to Telstra, with Optus and Vodafone networks service.",
    selectSubject: "Select subject",
    writeHere: "Write here",
    uploadYourFilesHere: "Upload your files here",
    regards: "Regards",
    issueOne:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultrices suscipit vehicula. Phasellus feugiat, velit nec volutpat pretium, massa metus blandit sem, et auctor est nisi at neque. Phasellus eget velit efficitur.",
    issueTwo:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultrices suscipit vehicula. Phasellus feugiat, velit nec volutpat pretium, massa metus blandit sem, et auctor est nisi at neque. Phasellus eget velit efficitur, posuere erat sit amet, mollis ante. Nunc eleifend nisl commodo facilisis dictum. Sed sodales iaculis euismod. Etiam auctor lectus sed tortor pulvinar aliquam. Etiam in ipsum odio. Duis ut orci gravida mauris semper suscipit.",
    totalTickets: "Total Tickets:",
    solved: "Solved",
    open: "Open",
    cancelled: "Cancelled",
    unrespond: "Unrespond",
    assignedAgent: "Assigned agent",
    alsoOnThisTickets: "Also on this ticket:",
    jobrSupportTeam: "Jobr.com Support Team",
    delivered: "Delivered",
    requestedRefund: "I have requested a refund",
    orderOvercharged: "Order was overcharged",
    didNotRecieve: "Did not received products",
    needMoreHelp: "Need more help",
    payment: "Payment",
    delivery: "Delivery",
    transfer: "Transfer",
    order: "Order",
    others: "Others",
    helpful: "Helpful",
    needMoreHelp: "No! I need more help",
    updateAccountInfo: "Update account information",
    forgotMypass: "Forgot my password",
    smsNotReceived: "SMS verification not received",
    delMyaccount: "Delete my account",
    thankYou: "Thank you",
    submitted: "Submitted",
    weWillGetBack: "We ‘ll get back to you soon",
    howToGetVerified: "How to get verified?",
  },
  mySupport: {
    heading: "Subject",
    lastRespond: "Last Respond",
    button: "Pending",
  },
  faq: {
    text1:
      "These terms and conditions outline the rules and regulations for the use of Company Name's Website, located at Website.com.",

    text2:
      " By accessing this website we assume you accept these terms and conditions. Do not continue to use Website Name if you do not agree to take all of the terms and conditions stated on this page.",

    text3:
      "The following terminology applies to these Terms and Conditions, Privacy Statement and Disclaimer Notice and all Agreements: “Client”, “You” and “Your” refers to you, the person log on this website and compliant to the Company's terms and conditions. “The Company”, “Ourselves”, “We”, “Our” and “Us”, refers to our Company. “Party”, “Parties”, or “Us”, refers to both the Client and ourselves. All terms refer to the offer, acceptance and consideration of payment necessary to undertake the process of our assistance to the Client in the most appropriate manner for the express purpose of meeting the Client's needs in respect of provision of the Company's stated services, in accordance with and subject to, prevailing law of Netherlands. Any use of the above terminology or other words in the singular, plural, capitalization and/or he/she or they, are taken as interchangeable and therefore as referring to same.",
  },

  checkout: {
    checkout: "Checkout",
    continueCheckout: "Continue to checkout",
  },

  kyc: {
    reviewStatus: "KYB Review Status",
    requestTitle: "Request KYC",
    requestKyb: "Request KYB",
    pending: "Status:  Pending",
    status: "Status:  ",
    verificationMsg:
      "Verification may take a few minutes, so make sure to refresh and check your status",
    kycReviewStatus: "KYC Review Status",
    refreshStatus: "Refresh Status",
    requestMessage:
      "We must verify that all users of the Sila platform are who they say they are. We do this by submitting end-user information for KYC review by our Identity Verification Partner. The  user will not be able to transact until the user is verified. With great power comes great responsibility ",
    continue: "Continue",
    heading: "Verification in Progress",
    description:
      "Once (KYC)checks are complete we’ll let you know via notification. This usually takes few minutes ",
    notify: "Sit Back ! We’ll notify you",
  },

  ageVerification: {
    headerTitle: "ID verification",
    header: "Proof of Age",
    header1: "ID verifications",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution",
    chooseIdentity: "Choose your identity type",
    upLoadId: "Upload your ID card",
    acceptOnly: "We accept only",
    cardType: "ID card, passport, driving licence",
    confirmIdentity: "Confirm your identity",
    button: "Submit",
    frontPhoto: "Front photo is required",
    backPhoto: "Back photo is required",
    chooseType: "Please select identity type",
  },
  supportTicket: {
    heading: "Open new ticket",
    subheading:
      "Our gateway is routed directly to Telstra, with Optus and Vodafone networks service.",
    uploadFile: "Upload your files here",
    button: "Submit",
    actionTitle: "Choose an option",
    galleryOption: "Gallery",
    cameraOption: "Camera",
    cancelOption: "Cancel",
  },

  card: {
    header: "Add a credit card",
    cardNo: "Card Number",
    card: "Card number",
    date: "mm/yy",
    cv: "123",
    cardName: "Card Holder name",
    ex: "Expiry",
    cvv: "CVV",
    name: "Card Holder Name",
    save: "Save this card for a faster checkout",
    text: "By saving your card you grant us your consent to store your payment method for future order. You can withdraw anytime",
    button: "Add Card",
    addBank: "Add Bank account",
    verifyCard: "Verify your card",
    chargeAmount:
      "We have charge a very small (Less than $1) amount from your card/bank",
    checkAccount: "Go to bank/check your account to know this amount.",
    getAmount: "Get that amount and verify ",
    validity: "(24 hours validity)",
    next: "Next",
  },
  successMessages: {
    loginSuccess: "Login successfully",
    otpSent: "OTP sent successfully",
    otpVerified: "OTP verified successfully",
    emailOtp: "OTP sent successfully! Please check your email",
    pinSet: "PIN set successfully",
    ticketSuccess: "Ticket created successfully",
    emptyList: "No records found",
    transactions: "No Transactions found",
    uploadDocument: "Document upload successfully",
    ticketSuccess: "Ticket created successfully",
    emptyList: "No record found",
    updateProfile: "Profile update succesfully",
  },
  payment: {
    header: "Payment methods",
    balance: "Available Balance",
    apple: "Apple pay",
    credit: "Add credit card",
    debit: "Add debit card",
    bank: "Connect your bank account",
    button: "Pay Now",
    success: "Successfully 25.00 JBR added",
    usd: "USD 25.00 paid",
    instruction: "Instructions",
    verified: "Verified",
    thankyou: "Thank you!",
    successverified: "Successfully verified",
    done: "Done",
    recentlyUsed: "Recently used",
    verify: "Verify Card",
    toVerifyCard: "To verify your account, enter the charged amount below",
    availableBalance: "Available methods",
    card: "Credit card **********5698",
    default: "Default",
    checkBalance: "Check Balance",
    redeem: "Redeem money",
    selectBank: "Select Bank Account",
    title: "Redeem",
    remove: "Remove Account",
    check: "Check Balance",
    accountHolder: "A/c Holder Name:  ",
    accountNo: "A/c No. - ",
    walletBalance: "Add Wallet Balance",
  },
  bank: {
    header: "Add bank account",
    routingLabel: "Routing Number",
    accountNameLabel: "Account Name",
    accountNoLabel: "Account Number",
    confirmAcc: "Confirm Account Number",
    accountType: "Account type",
    name: "Bank Name",
    namelabel: "Bank name",
    selectType: "Select account type",
    uploaded: "Documents are uploaded successfully",
    bank: "Linked Bank Accounts",
    clickToAdd: "+ Click to Add Bank Account",
    addBankAccount: "+ Add Bank Account",
    noBankAccount: "No Bank accounts found",
  },
  biometric: {
    setupBiometric: "Set up device biometrics to use this feature",
  },
  businessReg: {
    businessName: "Business Name",
    naicsType: "Select Naics Code",
    header: "Business Registration",
    doingBusiness: "Doing Business as",
    businessWebsite: "Business Website",
    businessType: "Select Business Type",
    employerIDNumber: "Employer Identification Number",
  },
  // Static strings

  //
  STATIC: {
    cardDetails: {
      userName: "Steven D. Daum",
      email: "steven.daum@gmail.com",
      phoneNo: "805-627-55874",
      companyName: "Company Name",
    },
    videoCall: {
      userName: "Senia PanFang",
    },
    makeAnOffer: {
      marlboroSilver: "Marlboro Silver",
      marlboro: "Marlboro",
      cigarettes: "Cigarettes",
      tobacco: "Tobacco",
    },

    businessCards: {
      userName: "Chad M. Johnson",
      companyName: "Company Name",
      address: "1457 New Street Heppner, OR 97836",
      email: "emailaddress@email.com",
      phone: "805-627-5874",
      apparel: "Apparel",
    },
    jbrWallet: {
      brands: "5 brands",
      productPurchases: "7 Products Purchases",
      manufacturers: "3 Manufacturers",
    },

    supportDetails: {
      userMessage:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultrices suscipit vehicula. Phasellus feugiat, velit nec volutpat pretium, massa metus blandit sem, et auctor est nisi at neque. Phasellus eget velit efficitur.",
      agentMessage:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ultrices suscipit vehicula. Phasellus feugiat, velit nec volutpat pretium, massa metus blandit sem, et auctor est nisi at neque. Phasellus eget velit efficitur, posuere erat sit amet, mollis ante. Nunc eleifend nisl commodo facilisis dictum. Sed sodales iaculis euismod. Etiam auctor lectus sed tortor pulvinar aliquam. Etiam in ipsum odio. Duis ut orci gravida mauris semper suscipit.",
      regards: "Regards",
      alsoOnTicket: "Also on this ticket:",
    },
    noDataFound: "No data found",
  },
};
