export const en = {
  common: {
    loading: "Loading",
    connectionError: "Connection error",
  },
  home: {
    header: "Home",
    message: "Welcome",
    variant: "App variant: ",
  },
  login: {
    username: "Username",
    usernameHint: "Enter your username",
    button: "Login",
    password: "Password",
    passwordHint: "Enter your password",
    invalidCredentials: "Invalid Username/Password",
  },
  profile: {
    header: "Profile",
    logout: "Logout",
    message: "This screen has the iOS native large header.",
  },
  splash: {
    register: "Register",
    signIn: "Sign in",
  },
  auth: {
    tellBusiness: "Tell us about your business",
    whichOne: "Which of the following best describes your business?",
    next: "Next",
    enterPin: "Enter your PIN for login",
    forgotPin: "Forgot PIN?",
    enterMobile: "Continue with your phone number",
    pleaseEnterMobile: "Please enter your number to phone number",
    mobilePlaceholder: "815-288-0329",
    continue: "Continue",
    verifyNumber: "Verify your",
    phoneNumber: "phone number",
    enterOtp: "Enter OTP code here",
    dontReceiveCode: "Didn’t receive Code?",
    resend: " Resend",
    setPin: "Set up PIN",
    cancel: "Cancel",
    enterYourPin: "Enter your PIN",
    logIn: "Log in",
    reEnterPin: "Reenter your PIN",
    done: "Done!",
    youVerified: "You are verified!",
    newPinSet: "Your new pin is set now",
  },
  search: {
    search: "search",
  },
  productInquiry: {
    productDetails: "Product Details",
    recomended: "Recomended products",
  },
  sendInquiry: {
    quantity: "Quantity",
    units: "Units of Measure",
  },
  startOrder: {
    checkout: "Checkout",
    delivery: "Delivery",
    startOrder: "Start Order",
    fedEx: "Fedex Express shipping",
    ups: "UPS Priority shipping",
    dhl: "DHL Standard shipping",
    jobr: "JOBR Standard shipping",
  },
};
