export const en = {
  common: {
    loading: "Loading",
    connectionError: "Connection error",
  },
  home: {
    header: "Home",
    message: "Welcome",
    variant: "App variant: ",
  },
  login: {
    username: "Username",
    usernameHint: "Enter your username",
    button: "Login",
    password: "Password",
    passwordHint: "Enter your password",
    invalidCredentials: "Invalid Username/Password",
  },
  profile: {
    header: "Profile",
    logout: "Logout",
    message: "This screen has the iOS native large header.",
  },
  splash: {
    register: "Register",
    signIn: "Sign in",
  },
  auth: {
    tellBusiness: "Tell us about your business",
    whichOne: "Which of the following best describes your business?",
    next: "Next",
    enterPin: "Enter your PIN for login",
    forgotPin: "Forgot PIN?",
    enterMobile: "Continue with your phone number",
    pleaseEnterMobile: "Please enter your number to phone number",
    mobilePlaceholder: "815-288-0329",
    continue: "Continue",
    verifyNumber: "Verify your",
    phoneNumber: "phone number",
    enterOtp: "Enter OTP code here",
    dontReceiveCode: "Didn’t receive Code?",
    resend: " Resend",
    setPin: "Set up PIN",
    cancel: "Cancel",
    enterYourPin: "Enter your PIN",
    logIn: "Log in",
    reEnterPin: "Reenter your PIN",
    done: "Done!",
    youVerified: "You are verified!",
    newPinSet: "Your new pin is set now",
  },
  search: {
    search: "search",
  },
  productInquiry: {
    productDetails: "Product Details",
    recomended: "Recomended products",
  },
  sendInquiry: {
    quantity: "Quantity",
    units: "Units of Measure",
  },
  startOrder: {
    checkout: "Checkout",
    delivery: "Delivery",
    startOrder: "Start Order",
    fedEx: "Fedex Express shipping",
    ups: "UPS Priority shipping",
    dhl: "DHL Standard shipping",
    jobr: "JOBR Standard shipping",
    done: "Done",
  },
  delivery: {
    reviewAndPayment: "Review & Payment",
    placeOrderMissingAddress: "Place Order (Missing address)",
  },
  AddShippingAddress: {
    addShippingAddress: "Shippping Address",
    save: "Save",
  },
  wallet: {
    agreement:
      "If you wish to purchase any product or service made available through Service (“Purchase”), you may be asked to supply certain information relevant to your Purchase including but not limited to, your credit or debit card number, the expiration date of your card, your billing address, and your shipping information.",
    wallet: "Wallet",
    close: "Close",
    useCoin:
      "Use coins to buy products from any listed stores and support/ tip to your rider",
    getJbr: "Get 15.00 JBR for every referral",
  },
  paymentMethod: {
    paymentMethod: "Payment methods",
    paynow: "Pay Now",
    addCreditCard: "Add Credit Card",
    applePay: "Apple Pay",
    addDebitCard: "Add Debit Card",
    connectBank: "Connect your bank account",
    availableBalance: "Available Balance",
    default: "Default",
  },
  addCreditCard: {
    addCreditCard: "Add a credit card",
    cardNumber: "Card Number",
    expiry: "Expiry",
    cvv: "CVV",
    cardHolderName: "Card Holder Name",
    sameShippingAddress: "Shipping address as same billing address",
    saveCard: "Save this card for a faster checkout",
    agreement:
      "By saving your card you grant us your consent to stor your payment method for future order. You can withdraw anytime.",
    monthYear: "mm/yy",
    cvvNo: "123",
    yes: "Yes",
    no: "No",
    addCard: "Add Card",
  },
};
